apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer    # Provision cloud LB (ELB on AWS)

# apiVersion: v1
# kind: Service
# metadata:
#   name: backend
#   labels:
#     app: backend
# spec:
#   type: LoadBalancer
#   selector:
#     app: backend
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 5000
