apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000        # Port exposed inside the cluster
      targetPort: 5000  # Port your container listens on
  type: ClusterIP      # Internal only, default type
# apiVersion: v1
# kind: Service
# metadata:
#   name: backend
#   labels:
#     app: backend
# spec:
#   type: LoadBalancer
#   selector:
#     app: backend
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 5000
