name: Backend Continuous Integration

on:
  pull_request:
    branches:
      - main
    paths:
      - 'starter/backend/**'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        working-directory: starter/backend
        run: pipenv install --deploy --ignore-pipfile

      - name: Install flake8
        working-directory: starter/backend
        run: pipenv run pip install flake8

      - name: Run flake8 lint
        working-directory: starter/backend
        run: pipenv run flake8 .

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: starter/backend
        run: pipenv install --deploy --ignore-pipfile

      - name: Run tests
        working-directory: starter/backend
        run: pipenv run pytest test_app.py

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v3

      - name: Build backend Docker image
        working-directory: starter/backend
        run: docker build -t backend-image:latest .
