name: Frontend CD

on:
  push:
    branches:
      - main
    paths:
      - 'starter/frontend/**'
      - '.github/workflows/frontend-cd.yaml'

jobs:
  deploy-frontend:
    name: Deploy React Frontend to EKS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Docker Image
        run: |
          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/frontend:latest
          docker build -t $IMAGE_URI ./starter/frontend
          docker push $IMAGE_URI

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-1 --name cluster

      - name: Deploy to EKS
        run: |
          kubectl apply -f ./starter/frontend/k8s/deployment.yaml
          kubectl apply -f ./starter/frontend/k8s/service.yaml
