name: Frontend CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:  # manual trigger

env:
  IMAGE_TAG: ${{ github.sha }}
  ECR_REPOSITORY: your-ecr-repo-name

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
        working-directory: ./starter/frontend
      - name: Run lint
        run: npm run lint
        working-directory: ./starter/frontend

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
        working-directory: ./starter/frontend
      - name: Run tests
        run: npm test -- --ci --reporters=default --reporters=jest-junit
        working-directory: ./starter/frontend

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]  # <- build runs only after lint and test succeed
    steps:
      - uses: actions/checkout@v3
      
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: us-east-1

      - name: Build Docker image
        run: |
          docker build \
            --build-arg REACT_APP_MOVIE_API_URL=https://your-backend-url.example.com \
            -t ${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} \
            ./starter/frontend

      - name: Push Docker image to ECR
        run: |
          docker push ${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
